version: '3.0'
services:
  postgres:
    container_name: Postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  authentication:
    image: quay.io/keycloak/keycloak:16.1.0
    container_name: Keyclock
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_SCHEMA: keycloak
      KEYCLOAK_USER: ${KEYCLOAK_USER:-admin}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD:-admin}
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  sonarqube:
    build: sonarqube
    container_name: sonarqube
    ports:
      - "9000:9000"

#  Nymph:
#    image: com.ambrosia.nymph:0.0.1-SNAPSHOT
#    name: Nymph
#    restart: on-failure
#    ports:
#      - 8888:8888

networks:
  database:
    driver: bridge

volumes:
  postgres:
