name: build/test
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x ./Nymph/gradlew
    - name: Test coverage with Gradle
      run: >
        ./Nymph/gradlew build
        ./Nymph/gradlew test
